- name: configure dispatch component
  hosts: dispatch
  become: yes
  tasks:
  - name: installing go 
    ansible.builtin.dnf:
      name: golang
      state: present
  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      home: /app
      system: true

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: download the dispatch floder
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip
      dest: /tmp/dispatch.zip
    
  - name: unzip the floder
    ansible.builtin.unarchive:
      src: /tmp/dispatch.zip
      dest: /app
      remote_src: true
  - name: reload the service
    ansible.builtin.systemd_service:
      daemon_reload:true
  - name: start and enable payment
    ansible.builtin.service:
      name: payment
      state: started
      enabled: yes