[mongodb]
172.31.43.42

[catalogue]
172.31.39.46




[redis]
redis.lakshmireddy.site

[mysql]
mysql.lakshmireddy.site

[rabbitmq]
rabbitmq.lakshmireddy.site

[dispatch]
dispatch.lakshmireddy.site

[user]
user.lakshmireddy.site

[cart]
cart.lakshmireddy.site

[shipping]
shipping.lakshmireddy.site


