[mongodb]
mongodb.

[redis]
redis.lakshmireddy.site

[mysql]
mysql.lakshmireddy.site

[rabbitmq]
rabbitmq.lakshmireddy.site

[dispatch]
dispatch.lakshmireddy.site

[user]
user.lakshmireddy.site

[cart]
cart.lakshmireddy.site

[shipping]
shipping.lakshmireddy.site

[catalogue]
catalogue.lakshmireddy.site
