- name: configure shipping component
  hosts: shipping
  become: yes
  tasks:
  - name: install maven
    ansible.builtin.dnf:
      name: maven 
      state: present

  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download the shipping code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
      dest: /tmp/shipping.zip

  - name: extract the  shipping files 
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes
- name: install maven dependecies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: rename the jar files
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
  args:
    chdir: /app

- name: copy shipping service
  ansible.builtin.copy:
    src: shipping.service
    dest: /etc/systemd/system/shipping.service

- name: reaload the catalogue service
  ansible.builtin.systemd_service:
    daemon_reload: true 

- name: start and enable the catalogue component
  ansible.builtin.service:
      name: catalogue
      state: started
      enable: yes